pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path. 
        maven "M398"
    }

    stages {
        stage('Echo Version'){
            steps {
                sh 'echo Print Maven Version'
                sh 'mvn -version'
            }
        }

        stage('Build'){
            steps{
                // Get some code from a Gitea repository
                git branch: 'main', url: 'http://139.84.159.194:5555/dasher-org/jenkins-hello-world.git'

                // Run Maven Package CMD
                sh "mvn clean package -DskipTests=true"

                // Archirve the artifact
                archiveArtifacts 'target/hello-demo-*.jar'
            }
        }

        stage('Unit Test'){
            steps {
                sh "mvn test"
                
                // Archirve unit tests
                junit(testResults: 'target/surefire-reports/TEST-*.xml', keepProperties: true, keepTestNames: true)
            }
        }
    }
}